import { StyleSheet } from 'react-native';

export const THEME_STORAGE_KEY = '@oleen-theme-preference-v1';

export const BRAND = {
  gold: '#C99B2E',
  blue: '#315D95',
  green: '#2D7D46',
  teal: '#167D7F',
  red: '#B94747',
  dark: '#2B2F36',
  purple: '#7A55A2',
};

export const LIGHT_COLORS = {
  gold: '#C99B2E',
  teal: '#167D7F',
  red: '#B94747',
  green: '#2D7D46',
  blue: '#315D95',
  bg: '#F7F5EF',
  panel: '#FFFFFF',
  panelSoft: '#FBFAF6',
  ink: '#1F2329',
  muted: '#6D7280',
  line: '#E7E0D2',
  goldSoft: '#FFF4CE',
  dark: '#2B2F36',
  onDark: '#FFFFFF',
  onDarkMuted: '#D8D2C5',
  walletBadge: '#3A3F48',
  stageBg: '#15181D',
  stageBorder: '#3A3F48',
  progressTrack: '#E8E2D4',
  successBg: '#EEF8F1',
  successBorder: '#BFDCC7',
  successSoft: '#EAF6EE',
  dangerSoftBg: '#FFF0F0',
  dangerSoftBorder: '#E8B6B6',
  primaryBtn: '#1F2329',
  primaryBtnText: '#FFFFFF',
};

export const DARK_COLORS = {
  gold: '#D4AB3F',
  teal: '#167D7F',
  red: '#E05C5C',
  green: '#3D9A57',
  blue: '#4A7FC4',
  bg: '#12151A',
  panel: '#1C2129',
  panelSoft: '#171B22',
  ink: '#F2EFE6',
  muted: '#A8ADB8',
  line: '#2E3540',
  goldSoft: '#3A3220',
  dark: '#0A0C0F',
  onDark: '#FFFFFF',
  onDarkMuted: '#C8C2B6',
  walletBadge: '#2A3039',
  stageBg: '#0A0C0F',
  stageBorder: '#2E3540',
  progressTrack: '#2E3540',
  successBg: '#1A2B22',
  successBorder: '#2D5C40',
  successSoft: '#1A2B22',
  dangerSoftBg: '#3A2222',
  dangerSoftBorder: '#6A4040',
  primaryBtn: '#D4AB3F',
  primaryBtnText: '#1F2329',
};

export function createStyles(c) {
  return StyleSheet.create({

  safeArea: {
    flex: 1,
    backgroundColor: c.dark,
  },
  shell: {
    flex: 1,
    backgroundColor: c.bg,
  },
  header: {
    minHeight: 86,
    backgroundColor: c.dark,
    paddingHorizontal: 18,
    paddingBottom: 16,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  brand: {
    color: c.gold,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  headerTitle: {
    color: c.onDark,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0,
  },
  headerCaption: {
    color: c.onDarkMuted,
    fontSize: 12,
    marginTop: 3,
  },
  walletBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: c.walletBadge,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  walletText: {
    color: c.onDark,
    fontSize: 13,
    fontWeight: '800',
  },
  contentWrap: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 20,
  },
  stack: {
    gap: 14,
  },
  stackSmall: {
    gap: 10,
  },
  flex: {
    flex: 1,
  },
  heroPanel: {
    backgroundColor: c.dark,
    borderRadius: 8,
    padding: 16,
    gap: 16,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoMark: {
    width: 58,
    height: 58,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.gold,
  },
  heroTitle: {
    color: c.onDark,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0,
  },
  heroText: {
    color: c.onDarkMuted,
    marginTop: 5,
    lineHeight: 20,
  },
  statusPanel: {
    backgroundColor: c.successBg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.successBorder,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  statusIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: c.panel,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusTitle: {
    color: c.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  statusText: {
    color: c.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statPill: {
    minWidth: 76,
    flexGrow: 1,
    backgroundColor: c.panelSoft,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  statValue: {
    color: c.ink,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  statLabel: {
    color: c.muted,
    fontSize: 12,
    marginTop: 2,
  },
  sectionTitle: {
    gap: 3,
  },
  sectionHeading: {
    color: c.ink,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: c.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  moduleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  moduleTile: {
    width: '48%',
    minHeight: 158,
    backgroundColor: c.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    padding: 12,
    gap: 10,
  },
  moduleIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moduleTitle: {
    color: c.ink,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 19,
  },
  moduleSubtitle: {
    color: c.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  proofGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  miniProof: {
    flex: 1,
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panel,
    padding: 10,
    justifyContent: 'center',
  },
  miniProofValue: {
    color: c.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  miniProofLabel: {
    color: c.muted,
    fontSize: 11,
    marginTop: 3,
  },
  card: {
    backgroundColor: c.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    padding: 14,
    gap: 12,
  },
  rowSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  rowBetweenTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  cardTitle: {
    color: c.ink,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 21,
  },
  smallMuted: {
    color: c.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  bodyText: {
    color: c.ink,
    fontSize: 14,
    lineHeight: 21,
  },
  videoStage: {
    backgroundColor: c.dark,
    borderRadius: 8,
    padding: 14,
    gap: 10,
  },
  videoFrame: {
    height: 184,
    backgroundColor: c.stageBg,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: c.stageBorder,
  },
  playButtonLarge: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoTitle: {
    color: c.onDark,
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: 0,
  },
  videoMeta: {
    color: c.onDarkMuted,
    fontSize: 13,
  },
  progressBar: {
    height: 8,
    borderRadius: 8,
    backgroundColor: c.progressTrack,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: c.gold,
    borderRadius: 8,
  },
  videoItemBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  videoThumb: {
    width: 58,
    height: 58,
    borderRadius: 8,
    backgroundColor: c.dark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoThumbActive: {
    backgroundColor: c.gold,
  },
  secondaryButton: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: c.ink,
    fontWeight: '800',
    fontSize: 14,
  },
  chipRow: {
    gap: 8,
    paddingRight: 16,
  },
  chip: {
    minHeight: 38,
    borderRadius: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panel,
  },
  chipActive: {
    backgroundColor: c.goldSoft,
    borderColor: c.gold,
  },
  chipText: {
    color: c.muted,
    fontWeight: '800',
    fontSize: 13,
  },
  chipTextActive: {
    color: c.ink,
  },
  timeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: c.goldSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  timeText: {
    color: c.ink,
    fontWeight: '900',
    fontSize: 12,
  },
  optionGrid: {
    gap: 8,
  },
  choiceButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  choiceButtonActive: {
    backgroundColor: c.goldSoft,
    borderColor: c.gold,
  },
  choiceText: {
    color: c.ink,
    fontWeight: '800',
    textAlign: 'center',
  },
  choiceTextActive: {
    color: c.ink,
  },
  feedback: {
    fontSize: 13,
    fontWeight: '900',
  },
  feedbackGood: {
    color: c.green,
  },
  feedbackBad: {
    color: c.red,
  },
  bettingHeader: {
    backgroundColor: c.dark,
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  balanceLabel: {
    color: c.onDarkMuted,
    fontSize: 13,
  },
  balance: {
    color: c.onDark,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
  },
  demoBadge: {
    backgroundColor: c.gold,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  demoBadgeText: {
    color: c.ink,
    fontWeight: '900',
  },
  outcomeGrid: {
    gap: 8,
  },
  outcomeButton: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  outcomeButtonActive: {
    borderColor: c.gold,
    backgroundColor: c.goldSoft,
  },
  outcomeLabel: {
    color: c.ink,
    fontWeight: '800',
    flex: 1,
  },
  oddsText: {
    color: c.green,
    fontWeight: '900',
  },
  betForm: {
    flexDirection: 'row',
    gap: 8,
  },
  stakeInput: {
    flex: 1,
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    color: c.ink,
    paddingHorizontal: 12,
    fontWeight: '900',
  },
  primaryButton: {
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: c.primaryBtn,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonText: {
    color: c.primaryBtnText,
    fontWeight: '900',
    fontSize: 14,
  },
  pendingBadge: {
    borderRadius: 8,
    backgroundColor: c.goldSoft,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  pendingText: {
    color: c.ink,
    fontWeight: '900',
    fontSize: 12,
  },
  ticketNumbers: {
    flexDirection: 'row',
    gap: 8,
  },
  dualButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  historyLine: {
    backgroundColor: c.panel,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  historyText: {
    color: c.ink,
    fontWeight: '800',
    flex: 1,
  },
  historyStatus: {
    fontWeight: '900',
  },
  emptyState: {
    minHeight: 68,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: c.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.panelSoft,
  },
  emptyText: {
    color: c.muted,
    fontWeight: '800',
  },
  instrumentMark: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 4,
    borderColor: c.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressText: {
    color: c.ink,
    fontWeight: '900',
    fontSize: 13,
  },
  iconAction: {
    width: 44,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.panelSoft,
    borderWidth: 1,
    borderColor: c.line,
  },
  iconActionDone: {
    backgroundColor: c.successSoft,
    borderColor: c.green,
  },
  liveStage: {
    backgroundColor: c.dark,
    borderRadius: 8,
    minHeight: 230,
    padding: 16,
    justifyContent: 'space-between',
    gap: 16,
  },
  liveTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  liveDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: c.red,
  },
  liveStatus: {
    color: c.red,
    fontWeight: '900',
    fontSize: 13,
  },
  liveTitle: {
    color: c.onDark,
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 32,
  },
  liveArtist: {
    color: c.onDarkMuted,
    fontSize: 15,
  },
  playerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  compactButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.panelSoft,
  },
  compactButtonActive: {
    backgroundColor: c.goldSoft,
    borderColor: c.gold,
  },
  profileRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: c.goldSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileBio: {
    color: c.ink,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  postInput: {
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    color: c.ink,
    padding: 12,
    textAlignVertical: 'top',
    lineHeight: 20,
  },
  categoryBadge: {
    backgroundColor: c.goldSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  categoryBadgeText: {
    color: c.ink,
    fontWeight: '900',
    fontSize: 12,
  },
  socialActions: {
    flexDirection: 'row',
    gap: 8,
  },
  socialAction: {
    minHeight: 38,
    minWidth: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 9,
  },
  socialActionActive: {
    borderColor: c.dangerSoftBorder,
    backgroundColor: c.dangerSoftBg,
  },
  socialActionText: {
    color: c.muted,
    fontWeight: '900',
  },
  socialActionTextActive: {
    color: c.red,
  },
  commentBubble: {
    backgroundColor: c.panelSoft,
    borderRadius: 8,
    padding: 10,
  },
  commentText: {
    color: c.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  commentForm: {
    flexDirection: 'row',
    gap: 8,
  },
  commentInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.panelSoft,
    color: c.ink,
    paddingHorizontal: 12,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.primaryBtn,
  },
  navWrap: {
    backgroundColor: c.panel,
    borderTopWidth: 1,
    borderTopColor: c.line,
  },
  nav: {
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  navItem: {
    minWidth: 76,
    minHeight: 50,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 8,
  },
  navItemActive: {
    backgroundColor: c.goldSoft,
  },
  navLabel: {
    color: c.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  navLabelActive: {
    color: c.ink,
  },

  });
}

export const lightStyles = createStyles(LIGHT_COLORS);
export const darkStyles = createStyles(DARK_COLORS);

export function getThemeBundle(themeName) {
  return themeName === 'dark'
    ? { colors: DARK_COLORS, styles: darkStyles }
    : { colors: LIGHT_COLORS, styles: lightStyles };
}
